// world-clock-ng/src/app/app.component.ts
import { Component } from '@angular/core';
import { City, TimeZone } from './app-types';
import axios, { AxiosResponse } from 'axios';
import { environment } from '../environments/environment';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  cityPrefix = '';
  availableCities: City[] = [];
  selectedCityIndex = -1;
  selectedCities: City[] = [];

  doAPICall(url: string, host: string, params: object): Promise<unknown> {
    return axios
      .get(url, {
        headers: {
          'x-rapidapi-key': environment.apiKey,
          useQueryString: true,
          'x-rapidapi-host': host,
        },
        params,
      })
      .then((r: AxiosResponse) => r.data);
  }
  showCities(): void {
    this.doAPICall(
      'https://wft-geo-db.p.rapidapi.com/v1/geo/cities',
      'wft-geo-db.p.rapidapi.com',
      {
        namePrefix: this.cityPrefix,
      }
    )
      .then((z: any) => z.data as City[])
      .then((cities: City[]) => {
        // console.log(cities);
        this.availableCities.splice(0);
        this.availableCities.push(...cities);
        this.selectedCityIndex = -1;
      });
  }
  onCitySelected(): void {
    const loc = this.availableCities[this.selectedCityIndex];
    this.doAPICall(
      'https://geocodeapi.p.rapidapi.com/GetTimezone',
      'geocodeapi.p.rapidapi.com',
      {
        latitude: loc.latitude,
        longitude: loc.longitude,
      }
    )
      .then((x: unknown) => x as TimeZone)
      .then((tz: TimeZone) => {
        // console.log("Geo details", tz);
        this.selectedCities.push({ ...loc, tz });
      });
  }

  apiKeyMissing(): boolean {
    return environment.apiKey === undefined || environment.apiKey === null;
  }
}

<style>
  :host {
    font-size: 14px;
    color: rgb(185, 40, 40);
    box-sizing: border-box;
  }
  #error {
    display: inline-block;
    border: 2px solid red;
    border-radius: 1em;
    padding: 0.5em;
    margin-bottom: 2em;
  }
</style>

<div class="content">
  <div id="error" *ngIf="apiKeyMissing()">
    Your setup is missing the .env file at the top of your project folder, or
    API_KEY is not defined in that file
  </div>
  <div>
    Enter city name (or its prefix)
    <input type="text" [(ngModel)]="cityPrefix" (blur)="showCities()" />
  </div>

  <ng-container *ngIf="availableCities.length > 0">
    <select
      id="city-select"
      [(ngModel)]="selectedCityIndex"
      (change)="onCitySelected()"
    >
      <option value="-1" disabled selected>Select a city</option>
      <option
        *ngFor="let c of availableCities; let pos = index"
        [attr.value]="pos"
      >
        {{ c.city }}, {{ c.country }}
      </option>
    </select>
  </ng-container>

  <div>
    <app-world-clock
      *ngFor="let c of selectedCities"
      [label]="c.city"
      [timeZone]="c.tz?.TimeZoneId"
      [gmtOffset]="c.tz?.GMT_offset"
    >
    </app-world-clock>
  </div>
</div>

// world-clock-vue/src/App.vue
<template>
  <div id="app">
    <div id="api-key-error" v-if="!API_KEY">
      <code>VUE_APP_API_KEY</code> is undefined.
      Create <code>.env</code> at the top of your project and insert.
      <pre>
      VUE_APP_API_KEY="your-rapid-api-key-goes-here"  
      </pre>
    </div>
    <p>Enter city name (or its first few letters) <input type="text"
        v-model.lazy="cityPrefix"></p>
    <template v-if="availableCities.length > 0">
      <label for="city-select">Choose a city</label>
      <select id="city-select" v-model.number="selectedCityIndex"
        @change="onCitySelected">
        <option value="-1" disabled selected>Select a city</option>
        <option v-for="(c,pos) in availableCities" :key="pos" :value="pos">
          {{c.city}}, {{c.country}} </option>

      </select>
    </template>
    <div id="time-wall">
      <WorldClock v-for="(c,pos) in selectedCities" :key="pos"
        @clock-removed="removeMe" :time-zone="c.tz.TimeZoneId"
        :gmt-offset="c.tz.GMT_offset" :label="c.city" />
    </div>
  </div>
</template>

<script lang="ts">
interface City {
  city: string;
  country: string;
  latitude: number;
  longitude: number;
  tz?: TimeZone;
}
interface TimeZone {
  Country: string;
  CountryId: string;
  GMT_offset: number;
  LocalTime_Now: string;
  TimeZoneId: string;
  TimeZoneName: string;
}
import { Component, Vue, Watch } from "vue-property-decorator";
import WorldClock from "./components/WorldClock.vue";
import axios, { AxiosResponse } from "axios";
@Component({
  components: {
    WorldClock,
  },
})
export default class App extends Vue {
  private cityPrefix = "";
  private availableCities: City[] = [];
  private selectedCityIndex = -1;
  private selectedCities: City[] = [];
  readonly API_KEY = process.env.VUE_APP_API_KEY;

  doAPICall(url: string, host: string, params: object): Promise<unknown> {
    return axios
      .get(url, {
        headers: {
          "x-rapidapi-key": process.env.VUE_APP_API_KEY,
          useQueryString: true,
          "x-rapidapi-host": host,
        },
        params,
      })
      .then((r: AxiosResponse) => r.data);
  }

  @Watch("cityPrefix")
  cityChanged() {
    // console.log("City has changed to", this.cityPrefix);
    this.doAPICall(
      "https://wft-geo-db.p.rapidapi.com/v1/geo/cities",
      "wft-geo-db.p.rapidapi.com",
      {
        namePrefix: this.cityPrefix,
        limit: 10,
      }
    )
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      .then((z: any) => z.data as City[])
      .then((cities: City[]) => {
        this.availableCities.splice(0);
        this.availableCities.push(...cities);
        this.selectedCityIndex = -1;
      });
  }

  onCitySelected() {
    const loc = this.availableCities[this.selectedCityIndex];
    this.doAPICall(
      "https://geocodeapi.p.rapidapi.com/GetTimezone",
      "geocodeapi.p.rapidapi.com",
      {
        latitude: loc.latitude,
        longitude: loc.longitude,
      }
    )
      .then((x: unknown) => x as TimeZone)
      .then((tz: TimeZone) => {
        // console.log("Geo details", tz);
        this.selectedCities.push({ ...loc, tz });
      });
  }

  removeMe(clockLabel: string) {
    console.log("Remove ", clockLabel);
    const idx = this.selectedCities.findIndex(
      (c: City) => c.city == clockLabel
    );
    if (idx >= 0) this.selectedCities.splice(idx, 1);
  }
}
</script>

<style>
#api-key-error {
  display: inline-block;
  padding: 1em;
  border: 2px solid red;
  border-radius: 1em;
}
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  /* text-align: center; */
  color: #2c3e50;
  margin-top: 60px;
}

#time-wall {
  margin-top: 16px;
}
</style>
